// ========================================================
// WIDA / WIDA - DOCTOR MODULE CLINICAL DATA REPOSITORY
// Module Owner: Vanshika Tailor
// ========================================================
// 1. All 30 Scalable Doctor Specializations
export const INITIAL_SPECIALIZATIONS = [
    { id: 1, name: 'General Physician', category: 'Primary Care', description: 'Comprehensive primary adult healthcare and preventative therapy', iconCode: 'Stethoscope' },
    { id: 2, name: 'Cardiologist', category: 'Cardiology', description: 'Specialist in cardiovascular diseases, rhythm disorders, and heart health', iconCode: 'HeartPulse' },
    { id: 3, name: 'Orthopedist', category: 'Orthopedics', description: 'Musculoskeletal medicine, bone fractures, and joint surgeries', iconCode: 'Bone' },
    { id: 4, name: 'Neurologist', category: 'Neurology', description: 'Disorders of the nervous system, brain, and spinal pathways', iconCode: 'Brain' },
    { id: 5, name: 'Dermatologist', category: 'Dermatology', description: 'Care of the skin, hair, nails, and allergic cutaneous manifestations', iconCode: 'Sparkles' },
    { id: 6, name: 'Pediatrician', category: 'Pediatrics', description: 'Comprehensive clinical care of infants, children, and young adolescents', iconCode: 'Baby' },
    { id: 7, name: 'Gynecologist', category: 'Women Health', description: 'Female reproductive health and preventive gynecology', iconCode: 'ShieldCheck' },
    { id: 8, name: 'Obstetrician', category: 'Women Health', description: 'Prenatal supervision, childbirth management, and postpartum health', iconCode: 'HeartHandshake' },
    { id: 9, name: 'Psychiatrist', category: 'Mental Health', description: 'Medical diagnosis and treatment of psychiatric conditions', iconCode: 'Smile' },
    { id: 10, name: 'Psychologist', category: 'Mental Health', description: 'Behavioral assessments, counseling, and psychotherapy', iconCode: 'Users' },
    { id: 11, name: 'ENT Specialist', category: 'Otolaryngology', description: 'Ear, nose, and throat diagnostics and head/neck surgery', iconCode: 'Headphones' },
    { id: 12, name: 'Ophthalmologist', category: 'Ophthalmology', description: 'Medical eye examinations, vision care, and microsurgical eye procedures', iconCode: 'Eye' },
    { id: 13, name: 'Dentist', category: 'Dental Care', description: 'Dentofacial aesthetics, teeth, oral hygiene, and surgical extractions', iconCode: 'Smile' },
    { id: 14, name: 'Endocrinologist', category: 'Endocrinology', description: 'Hormonal disorders, glycemic control, thyroid, and metabolic health', iconCode: 'Activity' },
    { id: 15, name: 'Gastroenterologist', category: 'Gastroenterology', description: 'Digestive tract, stomach, liver, pancreas, and biliary medicine', iconCode: 'Activity' },
    { id: 16, name: 'Pulmonologist', category: 'Pulmonology', description: 'Respiratory airways, bronchial health, and acute pulmonary conditions', iconCode: 'Wind' },
    { id: 17, name: 'Nephrologist', category: 'Nephrology', description: 'Renal function maintenance, dialysis, and electrolyte control', iconCode: 'Activity' },
    { id: 18, name: 'Urologist', category: 'Urology', description: 'Urinary system disorders and male reproductive surgeries', iconCode: 'Activity' },
    { id: 19, name: 'Oncologist', category: 'Oncology', description: 'Diagnosis and clinical management of benign and malignant tumors', iconCode: 'ShieldAlert' },
    { id: 20, name: 'Radiologist', category: 'Radiology', description: 'Interpretation of clinical diagnostic scans (MRI, CT, X-Ray, Sonography)', iconCode: 'Scan' },
    { id: 21, name: 'Pathologist', category: 'Pathology', description: 'Cellular and biopsy tissue laboratory diagnostic analyses', iconCode: 'Microscope' },
    { id: 22, name: 'Anesthesiologist', category: 'Anesthesia', description: 'Critical care, intensive pain management, and surgical anesthesia', iconCode: 'Shield' },
    { id: 23, name: 'Rheumatologist', category: 'Rheumatology', description: 'Autoimmune joint inflammation, lupus, and systemic arthritis', iconCode: 'Activity' },
    { id: 24, name: 'Infectious Disease Specialist', category: 'Infectious Disease', description: 'Bacterial, viral, fungal, and complex tropical infections', iconCode: 'ShieldAlert' },
    { id: 25, name: 'General Surgeon', category: 'Surgery', description: 'Operative procedures on abdominal visceral organs and soft tissues', iconCode: 'Scissors' },
    { id: 26, name: 'Neurosurgeon', category: 'Surgery', description: 'Surgical management of brain injuries, spine, and peripheral nerves', iconCode: 'Brain' },
    { id: 27, name: 'Cardiothoracic Surgeon', category: 'Surgery', description: 'Operative bypass and thoracic repair of cardiac valves and lungs', iconCode: 'HeartPulse' },
    { id: 28, name: 'Plastic Surgeon', category: 'Surgery', description: 'Reconstructive burn care, trauma surgery, and cosmetic procedures', iconCode: 'Sparkles' },
    { id: 29, name: 'Emergency Medicine Specialist', category: 'Emergency', description: 'Urgent resuscitation and immediate life support interventions', iconCode: 'Flame' },
    { id: 30, name: 'Family Medicine Specialist', category: 'Primary Care', description: 'Continuous and comprehensive family-centered healthcare', iconCode: 'Home' },
];
// 2. Demo Doctors across specialties
export const INITIAL_DOCTORS = [
    {
        id: 1,
        fullName: 'Dr. Aarav Sharma',
        email: 'aarav.sharma@wida.org',
        phoneNumber: '+91 98765 43210',
        gender: 'MALE',
        dateOfBirth: '1984-05-14',
        medicalRegistrationNumber: 'MCI-2009-48291',
        qualification: 'MBBS, MD (Cardiology), FACC',
        specializationId: 2,
        specializationName: 'Cardiologist',
        subSpecialization: 'Interventional Cardiology',
        yearsOfExperience: 14,
        hospitalClinicName: 'Apex Heart & Vascular Institute',
        address: 'Ring Road, Sector 5',
        city: 'New Delhi',
        state: 'Delhi',
        pincode: '110001',
        consultationFee: 800,
        languagesKnown: 'English, Hindi',
        professionalBio: 'Senior consultant interventional cardiologist with over 14 years of clinical experience in cardiac diagnostics, angiography, and lifestyle cardiology.',
        profilePhotoUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
        verificationStatus: 'VERIFIED',
        averageRating: 4.9,
        totalRatings: 128,
        totalPatients: 450,
        isActive: true,
    },
    {
        id: 2,
        fullName: 'Dr. Ananya Verma',
        email: 'ananya.verma@wida.org',
        phoneNumber: '+91 98765 43211',
        gender: 'FEMALE',
        dateOfBirth: '1987-09-22',
        medicalRegistrationNumber: 'MCI-2012-39201',
        qualification: 'MBBS, MS (Orthopedics)',
        specializationId: 3,
        specializationName: 'Orthopedist',
        subSpecialization: 'Joint Replacement & Sports Medicine',
        yearsOfExperience: 11,
        hospitalClinicName: 'City Bone & Joint Clinic',
        address: 'Bandra West, Hill Road',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400050',
        consultationFee: 750,
        languagesKnown: 'English, Hindi, Marathi',
        professionalBio: 'Specialized orthopedic surgeon focusing on knee and hip arthroplasty, sports injury rehabilitation, and minimally invasive bone surgeries.',
        profilePhotoUrl: 'https://images.unsplash.com/photo-1594824813682-1c2550ec1969?w=400&auto=format&fit=crop&q=80',
        verificationStatus: 'VERIFIED',
        averageRating: 4.85,
        totalRatings: 96,
        totalPatients: 320,
        isActive: true,
    },
    {
        id: 3,
        fullName: 'Dr. Rohan Mehta',
        email: 'rohan.mehta@wida.org',
        phoneNumber: '+91 98765 43212',
        gender: 'MALE',
        dateOfBirth: '1982-12-03',
        medicalRegistrationNumber: 'MCI-2007-88231',
        qualification: 'MBBS, DM (Neurology)',
        specializationId: 4,
        specializationName: 'Neurologist',
        subSpecialization: 'Stroke & Epilepsy Management',
        yearsOfExperience: 16,
        hospitalClinicName: 'Metro Neuro Care Hospital',
        address: 'Koramangala 4th Block',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560034',
        consultationFee: 900,
        languagesKnown: 'English, Hindi, Kannada',
        professionalBio: 'Renowned neurologist specialized in epilepsy management, neuro-rehab, stroke intervention, and acute migraine therapy.',
        profilePhotoUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
        verificationStatus: 'VERIFIED',
        averageRating: 4.92,
        totalRatings: 142,
        totalPatients: 510,
        isActive: true,
    },
    {
        id: 4,
        fullName: 'Dr. Kavya Singh',
        email: 'kavya.singh@wida.org',
        phoneNumber: '+91 98765 43213',
        gender: 'FEMALE',
        dateOfBirth: '1990-03-18',
        medicalRegistrationNumber: 'MCI-2015-11029',
        qualification: 'MBBS, MD (Dermatology)',
        specializationId: 5,
        specializationName: 'Dermatologist',
        subSpecialization: 'Clinical Dermatology & Trichology',
        yearsOfExperience: 8,
        hospitalClinicName: 'Aura Skin & Hair Clinic',
        address: 'Banjara Hills, Road No 12',
        city: 'Hyderabad',
        state: 'Telangana',
        pincode: '500034',
        consultationFee: 600,
        languagesKnown: 'English, Hindi, Telugu',
        professionalBio: 'Dedicated dermatologist with expertise in allergic skin reactions, acne scarring, eczema, and pediatric dermatological wellness.',
        profilePhotoUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
        verificationStatus: 'UNDER_REVIEW',
        averageRating: 4.78,
        totalRatings: 64,
        totalPatients: 210,
        isActive: true,
    },
    {
        id: 5,
        fullName: 'Dr. Rahul Gupta',
        email: 'rahul.gupta@wida.org',
        phoneNumber: '+91 98765 43214',
        gender: 'MALE',
        dateOfBirth: '1986-07-11',
        medicalRegistrationNumber: 'MCI-2011-94812',
        qualification: 'MBBS, DCH, DNB (Pediatrics)',
        specializationId: 6,
        specializationName: 'Pediatrician',
        subSpecialization: 'Neonatal & Child Healthcare',
        yearsOfExperience: 12,
        hospitalClinicName: 'Little Angels Children Clinic',
        address: 'Alwarpet, TTK Road',
        city: 'Chennai',
        state: 'Tamil Nadu',
        pincode: '600018',
        consultationFee: 650,
        languagesKnown: 'English, Hindi, Tamil',
        professionalBio: 'Compassionate pediatrician focused on early childhood immunization, developmental milestones, and pediatric respiratory conditions.',
        profilePhotoUrl: 'https://images.unsplash.com/photo-1622902046580-2b47f47f5471?w=400&auto=format&fit=crop&q=80',
        verificationStatus: 'VERIFIED',
        averageRating: 4.95,
        totalRatings: 180,
        totalPatients: 620,
        isActive: true,
    },
    {
        id: 6,
        fullName: 'Dr. Meera Joshi',
        email: 'meera.joshi@wida.org',
        phoneNumber: '+91 98765 43215',
        gender: 'FEMALE',
        dateOfBirth: '1985-11-29',
        medicalRegistrationNumber: 'MCI-2010-77401',
        qualification: 'MBBS, MS (Obstetrics & Gynecology)',
        specializationId: 7,
        specializationName: 'Gynecologist',
        subSpecialization: 'High-Risk Pregnancy & Laparoscopy',
        yearsOfExperience: 13,
        hospitalClinicName: 'Mother & Child Care Center',
        address: 'Shivaji Nagar',
        city: 'Pune',
        state: 'Maharashtra',
        pincode: '411005',
        consultationFee: 750,
        languagesKnown: 'English, Hindi, Marathi',
        professionalBio: 'Consultant gynecologist and obstetrician specializing in adolescent reproductive care, high-risk maternity, and laparoscopic surgeries.',
        profilePhotoUrl: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=400&auto=format&fit=crop&q=80',
        verificationStatus: 'VERIFIED',
        averageRating: 4.88,
        totalRatings: 115,
        totalPatients: 390,
        isActive: true,
    },
    {
        id: 7,
        fullName: 'Dr. Arjun Kapoor',
        email: 'arjun.kapoor@wida.org',
        phoneNumber: '+91 98765 43216',
        gender: 'MALE',
        dateOfBirth: '1989-01-15',
        medicalRegistrationNumber: 'MCI-2014-66231',
        qualification: 'MBBS, MD (General Medicine)',
        specializationId: 1,
        specializationName: 'General Physician',
        subSpecialization: 'Internal Medicine & Diabetes Care',
        yearsOfExperience: 9,
        hospitalClinicName: 'CareFirst Wellness Clinic',
        address: 'Salt Lake, Sector 1',
        city: 'Kolkata',
        state: 'West Bengal',
        pincode: '700064',
        consultationFee: 500,
        languagesKnown: 'English, Hindi, Bengali',
        professionalBio: 'Primary care clinician focused on holistic chronic illness management, seasonal fever control, hypertension, and preventative health.',
        profilePhotoUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&auto=format&fit=crop&q=80',
        verificationStatus: 'PENDING',
        averageRating: 4.7,
        totalRatings: 48,
        totalPatients: 180,
        isActive: true,
    },
];
// 3. Weekly Availability for Dr. Aarav Sharma
export const INITIAL_AVAILABILITY = {
    doctorId: 1,
    weeklySchedule: [
        { dayOfWeek: 'MONDAY', isAvailable: true, startTime: '09:00 AM', endTime: '05:00 PM', breakStartTime: '01:00 PM', breakEndTime: '02:00 PM', slotDurationMinutes: 30 },
        { dayOfWeek: 'TUESDAY', isAvailable: true, startTime: '09:00 AM', endTime: '05:00 PM', breakStartTime: '01:00 PM', breakEndTime: '02:00 PM', slotDurationMinutes: 30 },
        { dayOfWeek: 'WEDNESDAY', isAvailable: true, startTime: '09:00 AM', endTime: '01:00 PM', breakStartTime: '', breakEndTime: '', slotDurationMinutes: 30 },
        { dayOfWeek: 'THURSDAY', isAvailable: true, startTime: '09:00 AM', endTime: '05:00 PM', breakStartTime: '01:00 PM', breakEndTime: '02:00 PM', slotDurationMinutes: 30 },
        { dayOfWeek: 'FRIDAY', isAvailable: true, startTime: '09:00 AM', endTime: '05:00 PM', breakStartTime: '01:00 PM', breakEndTime: '02:00 PM', slotDurationMinutes: 30 },
        { dayOfWeek: 'SATURDAY', isAvailable: true, startTime: '10:00 AM', endTime: '02:00 PM', breakStartTime: '', breakEndTime: '', slotDurationMinutes: 30 },
        { dayOfWeek: 'SUNDAY', isAvailable: false, startTime: '00:00', endTime: '00:00', breakStartTime: '', breakEndTime: '', slotDurationMinutes: 30 },
    ],
};
// 4. Authorized Patients
export const INITIAL_PATIENTS = [
    {
        id: 1,
        patientId: 'PAT-1001',
        fullName: 'Rahul Verma',
        age: 42,
        gender: 'MALE',
        bloodGroup: 'B+',
        phone: '+91 98210 11223',
        email: 'rahul.verma@example.com',
        allergies: 'Penicillin, Dust mites',
        chronicConditions: 'Hypertension Stage 1',
        lastAppointmentDate: '2026-10-07',
        lastConsultationDate: '2026-09-28',
        status: 'Active Care',
    },
    {
        id: 2,
        patientId: 'PAT-1002',
        fullName: 'Priya Deshmukh',
        age: 36,
        gender: 'FEMALE',
        bloodGroup: 'O+',
        phone: '+91 98210 22334',
        email: 'priya.deshmukh@example.com',
        allergies: 'Sulfa antibiotics',
        chronicConditions: 'Mild Asthma',
        lastAppointmentDate: '2026-10-07',
        lastConsultationDate: '2026-09-20',
        status: 'Active Care',
    },
    {
        id: 3,
        patientId: 'PAT-1003',
        fullName: 'Vikramaditya Rao',
        age: 58,
        gender: 'MALE',
        bloodGroup: 'A+',
        phone: '+91 98210 33445',
        email: 'vikram.rao@example.com',
        allergies: 'None reported',
        chronicConditions: 'Type 2 Diabetes, Coronary Artery Disease',
        lastAppointmentDate: '2026-10-07',
        lastConsultationDate: '2026-08-14',
        status: 'Active Care',
    },
    {
        id: 4,
        patientId: 'PAT-1004',
        fullName: 'Sunita Sundaram',
        age: 64,
        gender: 'FEMALE',
        bloodGroup: 'AB+',
        phone: '+91 98210 44556',
        email: 'sunita.s@example.com',
        allergies: 'Aspirin (gastric sensitivity)',
        chronicConditions: 'Hyperlipidemia, Angina Pectoris',
        lastAppointmentDate: '2026-10-08',
        lastConsultationDate: '2026-08-01',
        status: 'Scheduled',
    },
    {
        id: 5,
        patientId: 'PAT-1005',
        fullName: 'Amitabh Sen',
        age: 29,
        gender: 'MALE',
        bloodGroup: 'O-',
        phone: '+91 98210 55667',
        email: 'amitabh.sen@example.com',
        allergies: 'None',
        chronicConditions: 'None',
        lastAppointmentDate: '2026-10-08',
        status: 'Pending Intake',
    },
];
// 5. Appointments for Dr. Aarav Sharma (Doctor 1)
export const INITIAL_APPOINTMENTS = [
    {
        id: 1,
        appointmentNumber: 'APT-2026-001',
        doctorId: 1,
        patientId: 'PAT-1001',
        patientName: 'Rahul Verma',
        appointmentDate: '2026-10-07',
        appointmentTime: '10:00 AM',
        appointmentType: 'IN_PERSON',
        reasonForVisit: 'Routine cardiac evaluation and recurring chest tightness on exertion',
        status: 'ACCEPTED',
        doctorNotes: 'Patient advised to bring past ECG reports.',
    },
    {
        id: 2,
        appointmentNumber: 'APT-2026-002',
        doctorId: 1,
        patientId: 'PAT-1002',
        patientName: 'Priya Deshmukh',
        appointmentDate: '2026-10-07',
        appointmentTime: '11:30 AM',
        appointmentType: 'VIDEO_CONSULTATION',
        reasonForVisit: 'Follow-up regarding palpitations and stress-induced tachycardia',
        status: 'PENDING',
    },
    {
        id: 3,
        appointmentNumber: 'APT-2026-003',
        doctorId: 1,
        patientId: 'PAT-1003',
        patientName: 'Vikramaditya Rao',
        appointmentDate: '2026-10-07',
        appointmentTime: '02:30 PM',
        appointmentType: 'IN_PERSON',
        reasonForVisit: 'Post-stenting 6-month arterial checkup and blood pressure review',
        status: 'ACCEPTED',
        doctorNotes: 'Review recent lipid profile prior to exam.',
    },
    {
        id: 4,
        appointmentNumber: 'APT-2026-004',
        doctorId: 1,
        patientId: 'PAT-1004',
        patientName: 'Sunita Sundaram',
        appointmentDate: '2026-10-08',
        appointmentTime: '09:30 AM',
        appointmentType: 'FOLLOW_UP',
        reasonForVisit: 'Review of recent echocardiogram results and statin tolerance',
        status: 'ACCEPTED',
    },
    {
        id: 5,
        appointmentNumber: 'APT-2026-005',
        doctorId: 1,
        patientId: 'PAT-1005',
        patientName: 'Amitabh Sen',
        appointmentDate: '2026-10-08',
        appointmentTime: '11:00 AM',
        appointmentType: 'IN_PERSON',
        reasonForVisit: 'Pre-marathon cardiovascular endurance and resting heart fitness assessment',
        status: 'PENDING',
    },
    {
        id: 6,
        appointmentNumber: 'APT-2026-006',
        doctorId: 1,
        patientId: 'PAT-1001',
        patientName: 'Rahul Verma',
        appointmentDate: '2026-09-28',
        appointmentTime: '10:00 AM',
        appointmentType: 'IN_PERSON',
        reasonForVisit: 'Initial consult for episodic tachycardia during morning walks',
        status: 'COMPLETED',
        doctorNotes: 'Consultation finished, prescribed beta blocker and requested lipid profile.',
    },
    {
        id: 7,
        appointmentNumber: 'APT-2026-007',
        doctorId: 1,
        patientId: 'PAT-1002',
        patientName: 'Priya Deshmukh',
        appointmentDate: '2026-09-20',
        appointmentTime: '03:00 PM',
        appointmentType: 'VIDEO_CONSULTATION',
        reasonForVisit: 'Review of thyroid panel and stress coping techniques',
        status: 'COMPLETED',
        doctorNotes: 'Thyroid normal, stress related tachycardia.',
    },
];
// 6. Consultations
export const INITIAL_CONSULTATIONS = [
    {
        id: 1,
        consultationNumber: 'CNS-2026-101',
        appointmentId: 6,
        doctorId: 1,
        patientId: 'PAT-1001',
        patientName: 'Rahul Verma',
        consultationDate: '2026-09-28',
        chiefComplaint: 'Mild palpitation and exercise fatigue on brisk walking',
        symptoms: 'Intermittent chest discomfort, occasional lightheadedness after stairs',
        clinicalNotes: 'BP: 138/88 mmHg, Heart Rate: 82 bpm, S1/S2 heard clearly, no carotid bruits.',
        diagnosis: 'Mild Sinus Tachycardia with Essential Stage 1 Hypertension',
        doctorRemarks: 'Advised 30 minutes light walking, low sodium dietary plan, avoid excessive caffeine.',
        followUpDate: '2026-10-07',
        additionalNotes: 'Ordered lipid profile and resting 12-lead ECG.',
        status: 'COMPLETED',
    },
    {
        id: 2,
        consultationNumber: 'CNS-2026-102',
        appointmentId: 7,
        doctorId: 1,
        patientId: 'PAT-1002',
        patientName: 'Priya Deshmukh',
        consultationDate: '2026-09-20',
        chiefComplaint: 'Racing pulse and anxiety during intense office work',
        symptoms: 'Sudden feeling of pounding heartbeat in chest, cold extremities',
        clinicalNotes: 'BP: 122/76 mmHg, Pulse: 94 bpm regular, lungs clear to auscultation.',
        diagnosis: 'Stress-Induced Autonomic Dysfunction',
        doctorRemarks: 'Practice diaphragmatic breathing exercises, stay well hydrated.',
        followUpDate: '2026-10-07',
        additionalNotes: 'Prescribed low-dose Propranolol SOS.',
        status: 'COMPLETED',
    },
];
// 7. Prescriptions
export const INITIAL_PRESCRIPTIONS = [
    {
        id: 1,
        prescriptionNumber: 'RX-2026-801',
        consultationId: 1,
        appointmentId: 6,
        doctorId: 1,
        doctorName: 'Dr. Aarav Sharma',
        doctorSpecialization: 'Cardiologist',
        doctorQualification: 'MBBS, MD (Cardiology), FACC',
        doctorClinic: 'Apex Heart & Vascular Institute',
        patientId: 'PAT-1001',
        patientName: 'Rahul Verma',
        prescriptionDate: '2026-09-28',
        generalAdvice: 'Take medicines strictly after meals. Monitor morning blood pressure daily.',
        pharmacyStatus: 'DISPENSED',
        items: [
            { id: 1, medicineName: 'Metoprolol Tartrate', dosage: '25 mg', frequency: 'Once daily', duration: '14 days', instructions: 'Take in the morning after breakfast' },
            { id: 2, medicineName: 'Telmisartan', dosage: '40 mg', frequency: 'Once daily', duration: '30 days', instructions: 'Take at night before bed' },
            { id: 3, medicineName: 'Atorvastatin', dosage: '10 mg', frequency: 'Once daily', duration: '30 days', instructions: 'Take with dinner' },
        ],
    },
    {
        id: 2,
        prescriptionNumber: 'RX-2026-802',
        consultationId: 2,
        appointmentId: 7,
        doctorId: 1,
        doctorName: 'Dr. Aarav Sharma',
        doctorSpecialization: 'Cardiologist',
        doctorQualification: 'MBBS, MD (Cardiology), FACC',
        doctorClinic: 'Apex Heart & Vascular Institute',
        patientId: 'PAT-1002',
        patientName: 'Priya Deshmukh',
        prescriptionDate: '2026-09-20',
        generalAdvice: 'Avoid sudden caffeine intake. Keep daily hydration above 2.5 liters.',
        pharmacyStatus: 'DISPENSED',
        items: [
            { id: 4, medicineName: 'Propranolol', dosage: '10 mg', frequency: 'As needed (SOS)', duration: '10 days', instructions: 'Take 1 tablet during severe palpitation episodes' },
            { id: 5, medicineName: 'Magnesium Glycinate', dosage: '200 mg', frequency: 'Once daily', duration: '20 days', instructions: 'Take at bedtime with water' },
        ],
    },
];
// 8. Diagnostic Test Requests
export const INITIAL_TEST_REQUESTS = [
    {
        id: 1,
        requestNumber: 'DTR-2026-401',
        doctorId: 1,
        doctorName: 'Dr. Aarav Sharma',
        patientId: 'PAT-1001',
        patientName: 'Rahul Verma',
        appointmentId: 1,
        testName: 'Lipid Profile',
        priority: 'ROUTINE',
        clinicalReason: 'Assess hyperlipidemia risk and baseline LDL/HDL before statin adjustment',
        specialInstructions: '12-hour overnight fasting required.',
        status: 'COMPLETED',
        requestedDate: '2026-09-29',
    },
    {
        id: 2,
        requestNumber: 'DTR-2026-402',
        doctorId: 1,
        doctorName: 'Dr. Aarav Sharma',
        patientId: 'PAT-1001',
        patientName: 'Rahul Verma',
        appointmentId: 1,
        testName: 'ECG 12-Lead',
        priority: 'ROUTINE',
        clinicalReason: 'Rule out ischemic ST changes and conduct baseline ventricular rhythm check',
        specialInstructions: 'Resting supine tracing.',
        status: 'COMPLETED',
        requestedDate: '2026-09-29',
    },
    {
        id: 3,
        requestNumber: 'DTR-2026-403',
        doctorId: 1,
        doctorName: 'Dr. Aarav Sharma',
        patientId: 'PAT-1002',
        patientName: 'Priya Deshmukh',
        appointmentId: 2,
        testName: 'Thyroid Profile (T3, T4, TSH)',
        priority: 'ROUTINE',
        clinicalReason: 'Rule out subclinical hyperthyroidism presenting as palpitations',
        specialInstructions: 'Early morning venous sample.',
        status: 'COMPLETED',
        requestedDate: '2026-09-21',
    },
    {
        id: 4,
        requestNumber: 'DTR-2026-404',
        doctorId: 1,
        doctorName: 'Dr. Aarav Sharma',
        patientId: 'PAT-1003',
        patientName: 'Vikramaditya Rao',
        appointmentId: 3,
        testName: '2D Echocardiogram',
        priority: 'URGENT',
        clinicalReason: 'Evaluate left ventricular ejection fraction and regional wall motion post-PTCA',
        specialInstructions: 'Compare with previous 2025 echocardiogram baseline.',
        status: 'REQUESTED',
        requestedDate: '2026-10-06',
    },
];
// 9. Diagnostic Medical Reports
export const INITIAL_REPORTS = [
    {
        id: 1,
        reportNumber: 'RPT-2026-901',
        patientId: 'PAT-1001',
        patientName: 'Rahul Verma',
        doctorId: 1,
        testRequestId: 1,
        testName: 'Lipid Profile',
        reportDate: '2026-09-30',
        resultSummary: 'Total Cholesterol: 218 mg/dL (Elevated), Triglycerides: 165 mg/dL, HDL: 44 mg/dL, LDL: 141 mg/dL. Statin adjustment indicated.',
        resultStatus: 'ABNORMAL',
        labTechnicianName: 'K. Murthy, Senior Biochemist',
        reportFileUrl: '/reports/rpt-901.pdf',
    },
    {
        id: 2,
        reportNumber: 'RPT-2026-902',
        patientId: 'PAT-1001',
        patientName: 'Rahul Verma',
        doctorId: 1,
        testRequestId: 2,
        testName: 'ECG 12-Lead',
        reportDate: '2026-09-30',
        resultSummary: 'Sinus rhythm, HR 78 bpm, normal axis. No acute ischemic ST elevation or depression. Non-specific minor T-wave flattening in lead III.',
        resultStatus: 'NORMAL',
        labTechnicianName: 'Dr. S. Nair, Consulting Radiologist',
        reportFileUrl: '/reports/rpt-902.pdf',
    },
    {
        id: 3,
        reportNumber: 'RPT-2026-903',
        patientId: 'PAT-1002',
        patientName: 'Priya Deshmukh',
        doctorId: 1,
        testRequestId: 3,
        testName: 'Thyroid Profile',
        reportDate: '2026-09-22',
        resultSummary: 'TSH: 2.15 uIU/mL (Normal: 0.4-4.2), Total T3: 110 ng/dL, Total T4: 8.2 ug/dL. Euthyroid state confirmed.',
        resultStatus: 'NORMAL',
        labTechnicianName: 'V. Saxena, Biochemist',
        reportFileUrl: '/reports/rpt-903.pdf',
    },
];
// 10. Achievements
export const INITIAL_ACHIEVEMENTS = [
    { id: 1, doctorId: 1, badgeKey: 'VERIFIED_DOCTOR', title: 'Verified Medical Specialist', description: 'National Medical Commission registry verified and authenticated', icon: 'BadgeCheck', isUnlocked: true, progress: 100, maxProgress: 100, awardedDate: '2026-01-15' },
    { id: 2, doctorId: 1, badgeKey: 'PATIENT_MILESTONE_100', title: '100+ Consultations Completed', description: 'Successfully conducted over 100 patient clinical consultations', icon: 'Users', isUnlocked: true, progress: 100, maxProgress: 100, awardedDate: '2026-04-10' },
    { id: 3, doctorId: 1, badgeKey: 'PATIENTS_SERVED_400', title: '400+ Patients Served', description: 'Provided compassionate care to more than 400 unique patients', icon: 'HeartHandshake', isUnlocked: true, progress: 450, maxProgress: 400, awardedDate: '2026-08-22' },
    { id: 4, doctorId: 1, badgeKey: 'TOP_RATED_SPECIALIST', title: 'Top Rated Specialist (4.9★)', description: 'Maintained exceptional average rating above 4.8 from verified patient visits', icon: 'Star', isUnlocked: true, progress: 100, maxProgress: 100, awardedDate: '2026-07-01' },
    { id: 5, doctorId: 1, badgeKey: 'CONSISTENT_AVAILABILITY', title: 'Consistent Availability Champion', description: 'Maintained 95%+ clinic punctuality and availability schedule adherence', icon: 'Clock', isUnlocked: true, progress: 96, maxProgress: 100, awardedDate: '2026-09-15' },
    { id: 6, doctorId: 1, badgeKey: 'DIAGNOSTIC_EXCELLENCE', title: 'Clinical Diagnostic Excellence', description: 'Recorded high correlation between clinical impressions and diagnostic investigations', icon: 'Activity', isUnlocked: true, progress: 100, maxProgress: 100, awardedDate: '2026-09-30' },
];
// 11. Ratings & Reviews
export const INITIAL_RATINGS = [
    {
        id: 1,
        doctorId: 1,
        patientName: 'Rahul Verma',
        ratingValue: 5,
        reviewTitle: 'Extremely knowledgeable and calm',
        reviewComment: 'Dr. Aarav explained my ECG results with great clarity. He did not rush through the consultation and created a realistic diet plan.',
        appointmentType: 'In-Person',
        createdAt: '2026-09-30 11:20:00',
    },
    {
        id: 2,
        doctorId: 1,
        patientName: 'Priya Deshmukh',
        ratingValue: 5,
        reviewTitle: 'Reassuring and thorough consultation',
        reviewComment: 'I was very anxious about my heart rate spikes. Dr. Aarav ruled out major issues and guided me gently. Feeling much better now.',
        appointmentType: 'Telehealth',
        createdAt: '2026-09-22 16:45:00',
    },
    {
        id: 3,
        doctorId: 1,
        patientName: 'Vikramaditya Rao',
        ratingValue: 5,
        reviewTitle: 'Exceptional post-stent management',
        reviewComment: 'Been consulting Dr. Aarav for 3 years. One of the finest cardiologists in Delhi. Truly professional and empathetic.',
        appointmentType: 'In-Person',
        createdAt: '2026-08-14 14:10:00',
    },
    {
        id: 4,
        doctorId: 1,
        patientName: 'Sunita Sundaram',
        ratingValue: 4,
        reviewTitle: 'Very good experience',
        reviewComment: 'Clinic was on time and doctor inspected all previous echo reports carefully. Prescriptions were clear.',
        appointmentType: 'Follow-up',
        createdAt: '2026-08-01 10:15:00',
    },
];
// 12. Notifications
export const INITIAL_NOTIFICATIONS = [
    {
        id: 1,
        doctorId: 1,
        title: 'New Appointment Request',
        message: 'Priya Deshmukh requested a Video Consultation appointment for today at 11:30 AM.',
        type: 'APPOINTMENT_REQUEST',
        referenceId: 'APT-2026-002',
        isRead: false,
        createdAt: '2026-10-07 08:30:00',
    },
    {
        id: 2,
        doctorId: 1,
        title: 'New Appointment Request',
        message: 'Amitabh Sen requested an In-Person appointment for tomorrow at 11:00 AM.',
        type: 'APPOINTMENT_REQUEST',
        referenceId: 'APT-2026-005',
        isRead: false,
        createdAt: '2026-10-07 09:15:00',
    },
    {
        id: 3,
        doctorId: 1,
        title: 'Diagnostic Lab Report Available',
        message: 'Lipid Profile report for patient Rahul Verma is now ready to view.',
        type: 'LAB_REPORT_READY',
        referenceId: 'RPT-2026-901',
        isRead: false,
        createdAt: '2026-10-06 17:00:00',
    },
    {
        id: 4,
        doctorId: 1,
        title: 'Prescription Dispensed',
        message: 'Prescription RX-2026-801 for Rahul Verma was fulfilled by WIDA Pharmacy.',
        type: 'PRESCRIPTION_ALERT',
        referenceId: 'RX-2026-801',
        isRead: true,
        createdAt: '2026-09-29 14:30:00',
    },
    {
        id: 5,
        doctorId: 1,
        title: 'System Verification Confirmed',
        message: 'Your National Medical Commission credentials have been re-verified successfully.',
        type: 'SYSTEM',
        referenceId: 'VERIF-101',
        isRead: true,
        createdAt: '2026-09-01 09:00:00',
    },
];
