import React, { useState } from 'react';
import { PrescriptionCard } from '../components/PrescriptionCard';
import { FileText, Search } from 'lucide-react';
export const PatientPrescriptions = ({ prescriptions, onOrderToPharmacy }) => {
    const [tab, setTab] = useState('Active');
    const [search, setSearch] = useState('');
    const filtered = prescriptions.filter((rx) => {
        const matchesTab = tab === 'All' ? true : rx.status === tab;
        const matchesSearch = rx.doctorName.toLowerCase().includes(search.toLowerCase()) ||
            rx.diagnosis.toLowerCase().includes(search.toLowerCase()) ||
            rx.medicines.some((m) => m.name.toLowerCase().includes(search.toLowerCase()));
        return matchesTab && matchesSearch;
    });
    return (<div className="patient-prescriptions d-flex flex-column gap-4">
      <div className="d-flex flex-wrap align-items-center justify-content-between gap-3">
        <div>
          <h3 className="font-heading mb-1">Prescription Management</h3>
          <p className="text-muted mb-0" style={{ fontSize: '0.88rem' }}>
            Digital prescriptions generated by certified physicians with instant pharmacy fulfillment
          </p>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="patient-card p-3 d-flex flex-wrap align-items-center justify-content-between gap-3">
        <div className="d-flex gap-1">
          {['Active', 'Completed', 'All'].map((t) => (<button key={t} className={`patient-btn patient-btn-sm ${tab === t ? 'patient-btn-primary' : 'patient-btn-outline'}`} onClick={() => setTab(t)}>
              {t} ({prescriptions.filter((p) => (t === 'All' ? true : p.status === t)).length})
            </button>))}
        </div>

        <div className="position-relative" style={{ minWidth: 260 }}>
          <Search size={14} className="position-absolute text-muted" style={{ top: '50%', transform: 'translateY(-50%)', left: 10 }}/>
          <input type="text" className="patient-input ps-4 py-1" style={{ fontSize: '0.85rem' }} placeholder="Search medicine or doctor..." value={search} onChange={(e) => setSearch(e.target.value)}/>
        </div>
      </div>

      {/* Prescription List */}
      {filtered.length === 0 ? (<div className="patient-card p-5 text-center text-muted">
          <FileText size={44} className="mb-2 text-muted mx-auto"/>
          <h5 className="font-heading">No prescriptions found</h5>
          <p style={{ fontSize: '0.85rem' }}>
            Your prescriptions will appear here automatically following your doctor consultations.
          </p>
        </div>) : (<div>
          {filtered.map((rx) => (<PrescriptionCard key={rx.id} prescription={rx} onOrderToPharmacy={onOrderToPharmacy}/>))}
        </div>)}
    </div>);
};
